export const RETRIEVE_STOCK_QUOTES_SUCCESS = 'RETRIEVE_STOCK_QUOTES_SUCCESS';

export const ADD_STOCK = 'ADD_STOCK';

export const DELETE_STOCK = 'DELETE_STOCK';

export const HANDLE_PROPERTY_SELECTED = 'HANDLE_PROPERTY_SELECTED';
